/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as ApiEnvPreflightRouteImport } from './routes/api/env-preflight'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAccountMfaRouteImport } from './routes/_authenticated/account.mfa'
import { Route as AuthenticatedAccountSecurityRouteImport } from './routes/_authenticated/account.security'
import { Route as AuthenticatedAccountSecurityChecklistRouteImport } from './routes/_authenticated/account.security-checklist'
import { Route as AuthenticatedAdminTenantsRouteImport } from './routes/_authenticated/admin.tenants'
import { Route as AuthenticatedAssessmentsIndexRouteImport } from './routes/_authenticated/assessments.index'
import { Route as AuthenticatedAssessmentsAssessmentIdRouteImport } from './routes/_authenticated/assessments.$assessmentId'
import { Route as AuthenticatedAssessmentsAnalyticsRouteImport } from './routes/_authenticated/assessments.analytics'
import { Route as AuthenticatedAssessmentsBankRouteImport } from './routes/_authenticated/assessments.bank'
import { Route as AuthenticatedAssessmentsNewRouteImport } from './routes/_authenticated/assessments.new'
import { Route as AuthenticatedAssignmentsIndexRouteImport } from './routes/_authenticated/assignments.index'
import { Route as AuthenticatedAssignmentsAssignmentIdRouteImport } from './routes/_authenticated/assignments.$assignmentId'
import { Route as AuthenticatedAssignmentsNewRouteImport } from './routes/_authenticated/assignments.new'
import { Route as AuthenticatedCurriculumIndexRouteImport } from './routes/_authenticated/curriculum.index'
import { Route as AuthenticatedCurriculumAnalyticsRouteImport } from './routes/_authenticated/curriculum.analytics'
import { Route as AuthenticatedCurriculumEnrollmentsRouteImport } from './routes/_authenticated/curriculum.enrollments'
import { Route as AuthenticatedCurriculumPlanRouteImport } from './routes/_authenticated/curriculum.plan'
import { Route as AuthenticatedCurriculumProgressRouteImport } from './routes/_authenticated/curriculum.progress'
import { Route as AuthenticatedCurriculumRightsRouteImport } from './routes/_authenticated/curriculum.rights'
import { Route as AuthenticatedCurriculumVersionsRouteImport } from './routes/_authenticated/curriculum.versions'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedMessagesConversationIdRouteImport } from './routes/_authenticated/messages.$conversationId'
import { Route as AuthenticatedMfaChallengeRouteImport } from './routes/_authenticated/mfa.challenge'
import { Route as AuthenticatedOrganizationIndexRouteImport } from './routes/_authenticated/organization.index'
import { Route as AuthenticatedOrganizationBillingRouteImport } from './routes/_authenticated/organization.billing'
import { Route as AuthenticatedOrganizationPeriodsRouteImport } from './routes/_authenticated/organization.periods'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students.index'
import { Route as AuthenticatedStudentsStudentIdRouteImport } from './routes/_authenticated/students.$studentId'
import { Route as AuthenticatedStudentsNewRouteImport } from './routes/_authenticated/students.new'
import { Route as AuthenticatedAssessmentsGradeSubmissionIdRouteImport } from './routes/_authenticated/assessments.grade.$submissionId'
import { Route as AuthenticatedAssessmentsTakeSubmissionIdRouteImport } from './routes/_authenticated/assessments.take.$submissionId'
import { Route as AuthenticatedCurriculumGradesGradeIdRouteImport } from './routes/_authenticated/curriculum.grades.$gradeId'
import { Route as AuthenticatedCurriculumLessonsLessonIdRouteImport } from './routes/_authenticated/curriculum.lessons.$lessonId'
import { Route as AuthenticatedCurriculumSubjectsSubjectIdRouteImport } from './routes/_authenticated/curriculum.subjects.$subjectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiEnvPreflightRoute = ApiEnvPreflightRouteImport.update({
  id: '/api/env-preflight',
  path: '/api/env-preflight',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountMfaRoute = AuthenticatedAccountMfaRouteImport.update({
  id: '/account/mfa',
  path: '/account/mfa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountSecurityRoute =
  AuthenticatedAccountSecurityRouteImport.update({
    id: '/account/security',
    path: '/account/security',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountSecurityChecklistRoute =
  AuthenticatedAccountSecurityChecklistRouteImport.update({
    id: '/account/security-checklist',
    path: '/account/security-checklist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTenantsRoute =
  AuthenticatedAdminTenantsRouteImport.update({
    id: '/admin/tenants',
    path: '/admin/tenants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsIndexRoute =
  AuthenticatedAssessmentsIndexRouteImport.update({
    id: '/assessments/',
    path: '/assessments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsAssessmentIdRoute =
  AuthenticatedAssessmentsAssessmentIdRouteImport.update({
    id: '/assessments/$assessmentId',
    path: '/assessments/$assessmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsAnalyticsRoute =
  AuthenticatedAssessmentsAnalyticsRouteImport.update({
    id: '/assessments/analytics',
    path: '/assessments/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsBankRoute =
  AuthenticatedAssessmentsBankRouteImport.update({
    id: '/assessments/bank',
    path: '/assessments/bank',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsNewRoute =
  AuthenticatedAssessmentsNewRouteImport.update({
    id: '/assessments/new',
    path: '/assessments/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssignmentsIndexRoute =
  AuthenticatedAssignmentsIndexRouteImport.update({
    id: '/assignments/',
    path: '/assignments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssignmentsAssignmentIdRoute =
  AuthenticatedAssignmentsAssignmentIdRouteImport.update({
    id: '/assignments/$assignmentId',
    path: '/assignments/$assignmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssignmentsNewRoute =
  AuthenticatedAssignmentsNewRouteImport.update({
    id: '/assignments/new',
    path: '/assignments/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCurriculumIndexRoute =
  AuthenticatedCurriculumIndexRouteImport.update({
    id: '/curriculum/',
    path: '/curriculum/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCurriculumAnalyticsRoute =
  AuthenticatedCurriculumAnalyticsRouteImport.update({
    id: '/curriculum/analytics',
    path: '/curriculum/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCurriculumEnrollmentsRoute =
  AuthenticatedCurriculumEnrollmentsRouteImport.update({
    id: '/curriculum/enrollments',
    path: '/curriculum/enrollments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCurriculumPlanRoute =
  AuthenticatedCurriculumPlanRouteImport.update({
    id: '/curriculum/plan',
    path: '/curriculum/plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCurriculumProgressRoute =
  AuthenticatedCurriculumProgressRouteImport.update({
    id: '/curriculum/progress',
    path: '/curriculum/progress',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCurriculumRightsRoute =
  AuthenticatedCurriculumRightsRouteImport.update({
    id: '/curriculum/rights',
    path: '/curriculum/rights',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCurriculumVersionsRoute =
  AuthenticatedCurriculumVersionsRouteImport.update({
    id: '/curriculum/versions',
    path: '/curriculum/versions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesConversationIdRoute =
  AuthenticatedMessagesConversationIdRouteImport.update({
    id: '/messages/$conversationId',
    path: '/messages/$conversationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMfaChallengeRoute =
  AuthenticatedMfaChallengeRouteImport.update({
    id: '/mfa/challenge',
    path: '/mfa/challenge',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationIndexRoute =
  AuthenticatedOrganizationIndexRouteImport.update({
    id: '/organization/',
    path: '/organization/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationBillingRoute =
  AuthenticatedOrganizationBillingRouteImport.update({
    id: '/organization/billing',
    path: '/organization/billing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationPeriodsRoute =
  AuthenticatedOrganizationPeriodsRouteImport.update({
    id: '/organization/periods',
    path: '/organization/periods',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsStudentIdRoute =
  AuthenticatedStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsNewRoute =
  AuthenticatedStudentsNewRouteImport.update({
    id: '/students/new',
    path: '/students/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsGradeSubmissionIdRoute =
  AuthenticatedAssessmentsGradeSubmissionIdRouteImport.update({
    id: '/assessments/grade/$submissionId',
    path: '/assessments/grade/$submissionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsTakeSubmissionIdRoute =
  AuthenticatedAssessmentsTakeSubmissionIdRouteImport.update({
    id: '/assessments/take/$submissionId',
    path: '/assessments/take/$submissionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCurriculumGradesGradeIdRoute =
  AuthenticatedCurriculumGradesGradeIdRouteImport.update({
    id: '/curriculum/grades/$gradeId',
    path: '/curriculum/grades/$gradeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCurriculumLessonsLessonIdRoute =
  AuthenticatedCurriculumLessonsLessonIdRouteImport.update({
    id: '/curriculum/lessons/$lessonId',
    path: '/curriculum/lessons/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCurriculumSubjectsSubjectIdRoute =
  AuthenticatedCurriculumSubjectsSubjectIdRouteImport.update({
    id: '/curriculum/subjects/$subjectId',
    path: '/curriculum/subjects/$subjectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/env-preflight': typeof ApiEnvPreflightRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/account/mfa': typeof AuthenticatedAccountMfaRoute
  '/account/security': typeof AuthenticatedAccountSecurityRoute
  '/account/security-checklist': typeof AuthenticatedAccountSecurityChecklistRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/assessments/$assessmentId': typeof AuthenticatedAssessmentsAssessmentIdRoute
  '/assessments/analytics': typeof AuthenticatedAssessmentsAnalyticsRoute
  '/assessments/bank': typeof AuthenticatedAssessmentsBankRoute
  '/assessments/new': typeof AuthenticatedAssessmentsNewRoute
  '/assignments/$assignmentId': typeof AuthenticatedAssignmentsAssignmentIdRoute
  '/assignments/new': typeof AuthenticatedAssignmentsNewRoute
  '/curriculum/analytics': typeof AuthenticatedCurriculumAnalyticsRoute
  '/curriculum/enrollments': typeof AuthenticatedCurriculumEnrollmentsRoute
  '/curriculum/plan': typeof AuthenticatedCurriculumPlanRoute
  '/curriculum/progress': typeof AuthenticatedCurriculumProgressRoute
  '/curriculum/rights': typeof AuthenticatedCurriculumRightsRoute
  '/curriculum/versions': typeof AuthenticatedCurriculumVersionsRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/mfa/challenge': typeof AuthenticatedMfaChallengeRoute
  '/organization/billing': typeof AuthenticatedOrganizationBillingRoute
  '/organization/periods': typeof AuthenticatedOrganizationPeriodsRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/students/new': typeof AuthenticatedStudentsNewRoute
  '/assessments/': typeof AuthenticatedAssessmentsIndexRoute
  '/assignments/': typeof AuthenticatedAssignmentsIndexRoute
  '/curriculum/': typeof AuthenticatedCurriculumIndexRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/organization/': typeof AuthenticatedOrganizationIndexRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
  '/assessments/grade/$submissionId': typeof AuthenticatedAssessmentsGradeSubmissionIdRoute
  '/assessments/take/$submissionId': typeof AuthenticatedAssessmentsTakeSubmissionIdRoute
  '/curriculum/grades/$gradeId': typeof AuthenticatedCurriculumGradesGradeIdRoute
  '/curriculum/lessons/$lessonId': typeof AuthenticatedCurriculumLessonsLessonIdRoute
  '/curriculum/subjects/$subjectId': typeof AuthenticatedCurriculumSubjectsSubjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/env-preflight': typeof ApiEnvPreflightRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/account/mfa': typeof AuthenticatedAccountMfaRoute
  '/account/security': typeof AuthenticatedAccountSecurityRoute
  '/account/security-checklist': typeof AuthenticatedAccountSecurityChecklistRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/assessments/$assessmentId': typeof AuthenticatedAssessmentsAssessmentIdRoute
  '/assessments/analytics': typeof AuthenticatedAssessmentsAnalyticsRoute
  '/assessments/bank': typeof AuthenticatedAssessmentsBankRoute
  '/assessments/new': typeof AuthenticatedAssessmentsNewRoute
  '/assignments/$assignmentId': typeof AuthenticatedAssignmentsAssignmentIdRoute
  '/assignments/new': typeof AuthenticatedAssignmentsNewRoute
  '/curriculum/analytics': typeof AuthenticatedCurriculumAnalyticsRoute
  '/curriculum/enrollments': typeof AuthenticatedCurriculumEnrollmentsRoute
  '/curriculum/plan': typeof AuthenticatedCurriculumPlanRoute
  '/curriculum/progress': typeof AuthenticatedCurriculumProgressRoute
  '/curriculum/rights': typeof AuthenticatedCurriculumRightsRoute
  '/curriculum/versions': typeof AuthenticatedCurriculumVersionsRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/mfa/challenge': typeof AuthenticatedMfaChallengeRoute
  '/organization/billing': typeof AuthenticatedOrganizationBillingRoute
  '/organization/periods': typeof AuthenticatedOrganizationPeriodsRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/students/new': typeof AuthenticatedStudentsNewRoute
  '/assessments': typeof AuthenticatedAssessmentsIndexRoute
  '/assignments': typeof AuthenticatedAssignmentsIndexRoute
  '/curriculum': typeof AuthenticatedCurriculumIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/organization': typeof AuthenticatedOrganizationIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/assessments/grade/$submissionId': typeof AuthenticatedAssessmentsGradeSubmissionIdRoute
  '/assessments/take/$submissionId': typeof AuthenticatedAssessmentsTakeSubmissionIdRoute
  '/curriculum/grades/$gradeId': typeof AuthenticatedCurriculumGradesGradeIdRoute
  '/curriculum/lessons/$lessonId': typeof AuthenticatedCurriculumLessonsLessonIdRoute
  '/curriculum/subjects/$subjectId': typeof AuthenticatedCurriculumSubjectsSubjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/env-preflight': typeof ApiEnvPreflightRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/account/mfa': typeof AuthenticatedAccountMfaRoute
  '/_authenticated/account/security': typeof AuthenticatedAccountSecurityRoute
  '/_authenticated/account/security-checklist': typeof AuthenticatedAccountSecurityChecklistRoute
  '/_authenticated/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/_authenticated/assessments/$assessmentId': typeof AuthenticatedAssessmentsAssessmentIdRoute
  '/_authenticated/assessments/analytics': typeof AuthenticatedAssessmentsAnalyticsRoute
  '/_authenticated/assessments/bank': typeof AuthenticatedAssessmentsBankRoute
  '/_authenticated/assessments/new': typeof AuthenticatedAssessmentsNewRoute
  '/_authenticated/assignments/$assignmentId': typeof AuthenticatedAssignmentsAssignmentIdRoute
  '/_authenticated/assignments/new': typeof AuthenticatedAssignmentsNewRoute
  '/_authenticated/curriculum/analytics': typeof AuthenticatedCurriculumAnalyticsRoute
  '/_authenticated/curriculum/enrollments': typeof AuthenticatedCurriculumEnrollmentsRoute
  '/_authenticated/curriculum/plan': typeof AuthenticatedCurriculumPlanRoute
  '/_authenticated/curriculum/progress': typeof AuthenticatedCurriculumProgressRoute
  '/_authenticated/curriculum/rights': typeof AuthenticatedCurriculumRightsRoute
  '/_authenticated/curriculum/versions': typeof AuthenticatedCurriculumVersionsRoute
  '/_authenticated/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/_authenticated/mfa/challenge': typeof AuthenticatedMfaChallengeRoute
  '/_authenticated/organization/billing': typeof AuthenticatedOrganizationBillingRoute
  '/_authenticated/organization/periods': typeof AuthenticatedOrganizationPeriodsRoute
  '/_authenticated/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/_authenticated/students/new': typeof AuthenticatedStudentsNewRoute
  '/_authenticated/assessments/': typeof AuthenticatedAssessmentsIndexRoute
  '/_authenticated/assignments/': typeof AuthenticatedAssignmentsIndexRoute
  '/_authenticated/curriculum/': typeof AuthenticatedCurriculumIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/organization/': typeof AuthenticatedOrganizationIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/_authenticated/assessments/grade/$submissionId': typeof AuthenticatedAssessmentsGradeSubmissionIdRoute
  '/_authenticated/assessments/take/$submissionId': typeof AuthenticatedAssessmentsTakeSubmissionIdRoute
  '/_authenticated/curriculum/grades/$gradeId': typeof AuthenticatedCurriculumGradesGradeIdRoute
  '/_authenticated/curriculum/lessons/$lessonId': typeof AuthenticatedCurriculumLessonsLessonIdRoute
  '/_authenticated/curriculum/subjects/$subjectId': typeof AuthenticatedCurriculumSubjectsSubjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/notifications'
    | '/onboarding'
    | '/api/env-preflight'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/account/mfa'
    | '/account/security'
    | '/account/security-checklist'
    | '/admin/tenants'
    | '/assessments/$assessmentId'
    | '/assessments/analytics'
    | '/assessments/bank'
    | '/assessments/new'
    | '/assignments/$assignmentId'
    | '/assignments/new'
    | '/curriculum/analytics'
    | '/curriculum/enrollments'
    | '/curriculum/plan'
    | '/curriculum/progress'
    | '/curriculum/rights'
    | '/curriculum/versions'
    | '/messages/$conversationId'
    | '/mfa/challenge'
    | '/organization/billing'
    | '/organization/periods'
    | '/students/$studentId'
    | '/students/new'
    | '/assessments/'
    | '/assignments/'
    | '/curriculum/'
    | '/messages/'
    | '/organization/'
    | '/students/'
    | '/assessments/grade/$submissionId'
    | '/assessments/take/$submissionId'
    | '/curriculum/grades/$gradeId'
    | '/curriculum/lessons/$lessonId'
    | '/curriculum/subjects/$subjectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/notifications'
    | '/onboarding'
    | '/api/env-preflight'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/account/mfa'
    | '/account/security'
    | '/account/security-checklist'
    | '/admin/tenants'
    | '/assessments/$assessmentId'
    | '/assessments/analytics'
    | '/assessments/bank'
    | '/assessments/new'
    | '/assignments/$assignmentId'
    | '/assignments/new'
    | '/curriculum/analytics'
    | '/curriculum/enrollments'
    | '/curriculum/plan'
    | '/curriculum/progress'
    | '/curriculum/rights'
    | '/curriculum/versions'
    | '/messages/$conversationId'
    | '/mfa/challenge'
    | '/organization/billing'
    | '/organization/periods'
    | '/students/$studentId'
    | '/students/new'
    | '/assessments'
    | '/assignments'
    | '/curriculum'
    | '/messages'
    | '/organization'
    | '/students'
    | '/assessments/grade/$submissionId'
    | '/assessments/take/$submissionId'
    | '/curriculum/grades/$gradeId'
    | '/curriculum/lessons/$lessonId'
    | '/curriculum/subjects/$subjectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/api/env-preflight'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/account/mfa'
    | '/_authenticated/account/security'
    | '/_authenticated/account/security-checklist'
    | '/_authenticated/admin/tenants'
    | '/_authenticated/assessments/$assessmentId'
    | '/_authenticated/assessments/analytics'
    | '/_authenticated/assessments/bank'
    | '/_authenticated/assessments/new'
    | '/_authenticated/assignments/$assignmentId'
    | '/_authenticated/assignments/new'
    | '/_authenticated/curriculum/analytics'
    | '/_authenticated/curriculum/enrollments'
    | '/_authenticated/curriculum/plan'
    | '/_authenticated/curriculum/progress'
    | '/_authenticated/curriculum/rights'
    | '/_authenticated/curriculum/versions'
    | '/_authenticated/messages/$conversationId'
    | '/_authenticated/mfa/challenge'
    | '/_authenticated/organization/billing'
    | '/_authenticated/organization/periods'
    | '/_authenticated/students/$studentId'
    | '/_authenticated/students/new'
    | '/_authenticated/assessments/'
    | '/_authenticated/assignments/'
    | '/_authenticated/curriculum/'
    | '/_authenticated/messages/'
    | '/_authenticated/organization/'
    | '/_authenticated/students/'
    | '/_authenticated/assessments/grade/$submissionId'
    | '/_authenticated/assessments/take/$submissionId'
    | '/_authenticated/curriculum/grades/$gradeId'
    | '/_authenticated/curriculum/lessons/$lessonId'
    | '/_authenticated/curriculum/subjects/$subjectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiEnvPreflightRoute: typeof ApiEnvPreflightRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/env-preflight': {
      id: '/api/env-preflight'
      path: '/api/env-preflight'
      fullPath: '/api/env-preflight'
      preLoaderRoute: typeof ApiEnvPreflightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/mfa': {
      id: '/_authenticated/account/mfa'
      path: '/account/mfa'
      fullPath: '/account/mfa'
      preLoaderRoute: typeof AuthenticatedAccountMfaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/security': {
      id: '/_authenticated/account/security'
      path: '/account/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AuthenticatedAccountSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/security-checklist': {
      id: '/_authenticated/account/security-checklist'
      path: '/account/security-checklist'
      fullPath: '/account/security-checklist'
      preLoaderRoute: typeof AuthenticatedAccountSecurityChecklistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tenants': {
      id: '/_authenticated/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AuthenticatedAdminTenantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/': {
      id: '/_authenticated/assessments/'
      path: '/assessments'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AuthenticatedAssessmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/$assessmentId': {
      id: '/_authenticated/assessments/$assessmentId'
      path: '/assessments/$assessmentId'
      fullPath: '/assessments/$assessmentId'
      preLoaderRoute: typeof AuthenticatedAssessmentsAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/analytics': {
      id: '/_authenticated/assessments/analytics'
      path: '/assessments/analytics'
      fullPath: '/assessments/analytics'
      preLoaderRoute: typeof AuthenticatedAssessmentsAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/bank': {
      id: '/_authenticated/assessments/bank'
      path: '/assessments/bank'
      fullPath: '/assessments/bank'
      preLoaderRoute: typeof AuthenticatedAssessmentsBankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/new': {
      id: '/_authenticated/assessments/new'
      path: '/assessments/new'
      fullPath: '/assessments/new'
      preLoaderRoute: typeof AuthenticatedAssessmentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments/': {
      id: '/_authenticated/assignments/'
      path: '/assignments'
      fullPath: '/assignments/'
      preLoaderRoute: typeof AuthenticatedAssignmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments/$assignmentId': {
      id: '/_authenticated/assignments/$assignmentId'
      path: '/assignments/$assignmentId'
      fullPath: '/assignments/$assignmentId'
      preLoaderRoute: typeof AuthenticatedAssignmentsAssignmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments/new': {
      id: '/_authenticated/assignments/new'
      path: '/assignments/new'
      fullPath: '/assignments/new'
      preLoaderRoute: typeof AuthenticatedAssignmentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum/': {
      id: '/_authenticated/curriculum/'
      path: '/curriculum'
      fullPath: '/curriculum/'
      preLoaderRoute: typeof AuthenticatedCurriculumIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum/analytics': {
      id: '/_authenticated/curriculum/analytics'
      path: '/curriculum/analytics'
      fullPath: '/curriculum/analytics'
      preLoaderRoute: typeof AuthenticatedCurriculumAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum/enrollments': {
      id: '/_authenticated/curriculum/enrollments'
      path: '/curriculum/enrollments'
      fullPath: '/curriculum/enrollments'
      preLoaderRoute: typeof AuthenticatedCurriculumEnrollmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum/plan': {
      id: '/_authenticated/curriculum/plan'
      path: '/curriculum/plan'
      fullPath: '/curriculum/plan'
      preLoaderRoute: typeof AuthenticatedCurriculumPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum/progress': {
      id: '/_authenticated/curriculum/progress'
      path: '/curriculum/progress'
      fullPath: '/curriculum/progress'
      preLoaderRoute: typeof AuthenticatedCurriculumProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum/rights': {
      id: '/_authenticated/curriculum/rights'
      path: '/curriculum/rights'
      fullPath: '/curriculum/rights'
      preLoaderRoute: typeof AuthenticatedCurriculumRightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum/versions': {
      id: '/_authenticated/curriculum/versions'
      path: '/curriculum/versions'
      fullPath: '/curriculum/versions'
      preLoaderRoute: typeof AuthenticatedCurriculumVersionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$conversationId': {
      id: '/_authenticated/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof AuthenticatedMessagesConversationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mfa/challenge': {
      id: '/_authenticated/mfa/challenge'
      path: '/mfa/challenge'
      fullPath: '/mfa/challenge'
      preLoaderRoute: typeof AuthenticatedMfaChallengeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organization/': {
      id: '/_authenticated/organization/'
      path: '/organization'
      fullPath: '/organization/'
      preLoaderRoute: typeof AuthenticatedOrganizationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organization/billing': {
      id: '/_authenticated/organization/billing'
      path: '/organization/billing'
      fullPath: '/organization/billing'
      preLoaderRoute: typeof AuthenticatedOrganizationBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organization/periods': {
      id: '/_authenticated/organization/periods'
      path: '/organization/periods'
      fullPath: '/organization/periods'
      preLoaderRoute: typeof AuthenticatedOrganizationPeriodsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$studentId': {
      id: '/_authenticated/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/new': {
      id: '/_authenticated/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof AuthenticatedStudentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/grade/$submissionId': {
      id: '/_authenticated/assessments/grade/$submissionId'
      path: '/assessments/grade/$submissionId'
      fullPath: '/assessments/grade/$submissionId'
      preLoaderRoute: typeof AuthenticatedAssessmentsGradeSubmissionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments/take/$submissionId': {
      id: '/_authenticated/assessments/take/$submissionId'
      path: '/assessments/take/$submissionId'
      fullPath: '/assessments/take/$submissionId'
      preLoaderRoute: typeof AuthenticatedAssessmentsTakeSubmissionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum/grades/$gradeId': {
      id: '/_authenticated/curriculum/grades/$gradeId'
      path: '/curriculum/grades/$gradeId'
      fullPath: '/curriculum/grades/$gradeId'
      preLoaderRoute: typeof AuthenticatedCurriculumGradesGradeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum/lessons/$lessonId': {
      id: '/_authenticated/curriculum/lessons/$lessonId'
      path: '/curriculum/lessons/$lessonId'
      fullPath: '/curriculum/lessons/$lessonId'
      preLoaderRoute: typeof AuthenticatedCurriculumLessonsLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum/subjects/$subjectId': {
      id: '/_authenticated/curriculum/subjects/$subjectId'
      path: '/curriculum/subjects/$subjectId'
      fullPath: '/curriculum/subjects/$subjectId'
      preLoaderRoute: typeof AuthenticatedCurriculumSubjectsSubjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedAccountMfaRoute: typeof AuthenticatedAccountMfaRoute
  AuthenticatedAccountSecurityRoute: typeof AuthenticatedAccountSecurityRoute
  AuthenticatedAccountSecurityChecklistRoute: typeof AuthenticatedAccountSecurityChecklistRoute
  AuthenticatedAdminTenantsRoute: typeof AuthenticatedAdminTenantsRoute
  AuthenticatedAssessmentsAssessmentIdRoute: typeof AuthenticatedAssessmentsAssessmentIdRoute
  AuthenticatedAssessmentsAnalyticsRoute: typeof AuthenticatedAssessmentsAnalyticsRoute
  AuthenticatedAssessmentsBankRoute: typeof AuthenticatedAssessmentsBankRoute
  AuthenticatedAssessmentsNewRoute: typeof AuthenticatedAssessmentsNewRoute
  AuthenticatedAssignmentsAssignmentIdRoute: typeof AuthenticatedAssignmentsAssignmentIdRoute
  AuthenticatedAssignmentsNewRoute: typeof AuthenticatedAssignmentsNewRoute
  AuthenticatedCurriculumAnalyticsRoute: typeof AuthenticatedCurriculumAnalyticsRoute
  AuthenticatedCurriculumEnrollmentsRoute: typeof AuthenticatedCurriculumEnrollmentsRoute
  AuthenticatedCurriculumPlanRoute: typeof AuthenticatedCurriculumPlanRoute
  AuthenticatedCurriculumProgressRoute: typeof AuthenticatedCurriculumProgressRoute
  AuthenticatedCurriculumRightsRoute: typeof AuthenticatedCurriculumRightsRoute
  AuthenticatedCurriculumVersionsRoute: typeof AuthenticatedCurriculumVersionsRoute
  AuthenticatedMessagesConversationIdRoute: typeof AuthenticatedMessagesConversationIdRoute
  AuthenticatedMfaChallengeRoute: typeof AuthenticatedMfaChallengeRoute
  AuthenticatedOrganizationBillingRoute: typeof AuthenticatedOrganizationBillingRoute
  AuthenticatedOrganizationPeriodsRoute: typeof AuthenticatedOrganizationPeriodsRoute
  AuthenticatedStudentsStudentIdRoute: typeof AuthenticatedStudentsStudentIdRoute
  AuthenticatedStudentsNewRoute: typeof AuthenticatedStudentsNewRoute
  AuthenticatedAssessmentsIndexRoute: typeof AuthenticatedAssessmentsIndexRoute
  AuthenticatedAssignmentsIndexRoute: typeof AuthenticatedAssignmentsIndexRoute
  AuthenticatedCurriculumIndexRoute: typeof AuthenticatedCurriculumIndexRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedOrganizationIndexRoute: typeof AuthenticatedOrganizationIndexRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
  AuthenticatedAssessmentsGradeSubmissionIdRoute: typeof AuthenticatedAssessmentsGradeSubmissionIdRoute
  AuthenticatedAssessmentsTakeSubmissionIdRoute: typeof AuthenticatedAssessmentsTakeSubmissionIdRoute
  AuthenticatedCurriculumGradesGradeIdRoute: typeof AuthenticatedCurriculumGradesGradeIdRoute
  AuthenticatedCurriculumLessonsLessonIdRoute: typeof AuthenticatedCurriculumLessonsLessonIdRoute
  AuthenticatedCurriculumSubjectsSubjectIdRoute: typeof AuthenticatedCurriculumSubjectsSubjectIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedAccountMfaRoute: AuthenticatedAccountMfaRoute,
  AuthenticatedAccountSecurityRoute: AuthenticatedAccountSecurityRoute,
  AuthenticatedAccountSecurityChecklistRoute:
    AuthenticatedAccountSecurityChecklistRoute,
  AuthenticatedAdminTenantsRoute: AuthenticatedAdminTenantsRoute,
  AuthenticatedAssessmentsAssessmentIdRoute:
    AuthenticatedAssessmentsAssessmentIdRoute,
  AuthenticatedAssessmentsAnalyticsRoute:
    AuthenticatedAssessmentsAnalyticsRoute,
  AuthenticatedAssessmentsBankRoute: AuthenticatedAssessmentsBankRoute,
  AuthenticatedAssessmentsNewRoute: AuthenticatedAssessmentsNewRoute,
  AuthenticatedAssignmentsAssignmentIdRoute:
    AuthenticatedAssignmentsAssignmentIdRoute,
  AuthenticatedAssignmentsNewRoute: AuthenticatedAssignmentsNewRoute,
  AuthenticatedCurriculumAnalyticsRoute: AuthenticatedCurriculumAnalyticsRoute,
  AuthenticatedCurriculumEnrollmentsRoute:
    AuthenticatedCurriculumEnrollmentsRoute,
  AuthenticatedCurriculumPlanRoute: AuthenticatedCurriculumPlanRoute,
  AuthenticatedCurriculumProgressRoute: AuthenticatedCurriculumProgressRoute,
  AuthenticatedCurriculumRightsRoute: AuthenticatedCurriculumRightsRoute,
  AuthenticatedCurriculumVersionsRoute: AuthenticatedCurriculumVersionsRoute,
  AuthenticatedMessagesConversationIdRoute:
    AuthenticatedMessagesConversationIdRoute,
  AuthenticatedMfaChallengeRoute: AuthenticatedMfaChallengeRoute,
  AuthenticatedOrganizationBillingRoute: AuthenticatedOrganizationBillingRoute,
  AuthenticatedOrganizationPeriodsRoute: AuthenticatedOrganizationPeriodsRoute,
  AuthenticatedStudentsStudentIdRoute: AuthenticatedStudentsStudentIdRoute,
  AuthenticatedStudentsNewRoute: AuthenticatedStudentsNewRoute,
  AuthenticatedAssessmentsIndexRoute: AuthenticatedAssessmentsIndexRoute,
  AuthenticatedAssignmentsIndexRoute: AuthenticatedAssignmentsIndexRoute,
  AuthenticatedCurriculumIndexRoute: AuthenticatedCurriculumIndexRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedOrganizationIndexRoute: AuthenticatedOrganizationIndexRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
  AuthenticatedAssessmentsGradeSubmissionIdRoute:
    AuthenticatedAssessmentsGradeSubmissionIdRoute,
  AuthenticatedAssessmentsTakeSubmissionIdRoute:
    AuthenticatedAssessmentsTakeSubmissionIdRoute,
  AuthenticatedCurriculumGradesGradeIdRoute:
    AuthenticatedCurriculumGradesGradeIdRoute,
  AuthenticatedCurriculumLessonsLessonIdRoute:
    AuthenticatedCurriculumLessonsLessonIdRoute,
  AuthenticatedCurriculumSubjectsSubjectIdRoute:
    AuthenticatedCurriculumSubjectsSubjectIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiEnvPreflightRoute: ApiEnvPreflightRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
